/**
 * Contract-send EXECUTION — B9-08 / INV-63, Jess Gate correction round 2,
 * 2026-09-12 ("one server-verifiable, single-use send authorization
 * boundary covering BOTH reservation and actual provider send").
 *
 * POST /.netlify/functions/ghl-contract-send-execute
 * body: { opportunityId, versionRaw, attemptId, templateId }
 *
 * THIS IS NOW THE ONLY PATH TO GHL'S `POST /proposals/templates/send`.
 * `ghl-proxy.ts`'s generic allowlist no longer includes that path at
 * all -- a direct call through the browser-facing proxy 404s (falls
 * through to "not allowlisted"), exactly matching this correction
 * round's item 4 ("a direct call to /proposals/templates/send must fail
 * closed unless it carries server-verifiable authorization generated by
 * the approved reservation path"). The two remaining `/proposals/...`
 * paths still reachable through `ghl-proxy.ts` (`GET /proposals/templates`,
 * `GET /proposals/document`) are read-only discovery/readback and carry
 * no send capability -- moving them here too would not add any safety,
 * only complexity.
 *
 * REDEEMS A TICKET, NEVER ISSUES ONE. `ghl-contract-send-reserve.ts` is
 * the ONLY place that writes the "in_progress" note (after independently
 * verifying Brad authorization currency -- see `lib/authorization-guard.ts`)
 * -- that note IS the single-use ticket. This function's job is narrowly:
 * confirm a ticket exists for EXACTLY the declared
 * {attemptId, opportunityId, versionRaw, templateId}, confirm it is
 * still in the `in_progress` state (never already consumed by an earlier
 * resolution), RE-VERIFY authorization currency independently (never
 * trusting that reservation's own check still holds -- narrows, does not
 * eliminate, the time-of-check-to-time-of-use window between the two
 * calls), and ONLY THEN forward the real send to GHL.
 *
 * SINGLE-USE, NARROWED NOT ELIMINATED. GHL's Notes API exposes no
 * compare-and-swap or unique-constraint primitive (documented already in
 * `ghl-contract-send-reserve.ts`'s own header) -- this function reads
 * notes fresh immediately before forwarding, which narrows the replay
 * window to this one function's own round-trip duration, the SAME
 * accepted, reported residual `ghl-contract-send-reserve.ts` already
 * discloses for its own conflict check. A genuinely simultaneous double-
 * invocation of THIS function for the SAME attemptId remains a known,
 * unclosed edge case -- reported, not hidden. The client's own
 * subsequent write of the provisional/final resolution note (unchanged,
 * `ContractWorkspace.tsx`'s `handleSend`) is what actually transitions
 * the ticket out of `in_progress` for future reads; this function does
 * not write anything itself.
 *
 * `contactId`, `userId`, and `templateId` are ALL resolved from config,
 * never accepted from the caller for the outbound GHL body -- identical
 * to `ghl-proxy.ts`'s former GATE 2 override, which this function fully
 * replaces for the send path.
 */

import {
  getConfig, SENDER_USER_ID_NOT_CONFIGURED, POPULATION_VERIFIED,
} from "../../shared/ghl-config";
import { resolveAttemptByExactId } from "./lib/contract-send-guard";
import { verifyServerSideAuthorization } from "./lib/authorization-guard";

const GHL_BASE = "https://services.leadconnectorhq.com";
const { locationId: LOCATION_ID, documentsContracts: DOCUMENTS_CONTRACTS } = getConfig(process.env.IAOS_ENV);
const TEST_LOCATION_ID = getConfig("test").locationId;

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

export const handler = async (event: any) => {
  if (event.httpMethod === "OPTIONS") return { statusCode: 204, headers: CORS, body: "" };
  if (event.httpMethod !== "POST") return { statusCode: 405, headers: CORS, body: "Method Not Allowed" };

  if (LOCATION_ID !== TEST_LOCATION_ID) {
    return { statusCode: 403, headers: CORS, body: JSON.stringify({ error: "Forbidden", by: "iaos-contract-send-execute-test-only" }) };
  }
  if (DOCUMENTS_CONTRACTS.senderUserId === SENDER_USER_ID_NOT_CONFIGURED) {
    return { statusCode: 500, headers: CORS, body: JSON.stringify({ error: "senderUserId not configured", by: "iaos-contract-send-execute-test-only" }) };
  }
  if (DOCUMENTS_CONTRACTS.populationVerification !== POPULATION_VERIFIED) {
    return { statusCode: 500, headers: CORS, body: JSON.stringify({ error: "template population not verified", by: "iaos-contract-send-execute-test-only" }) };
  }

  let payload: Record<string, unknown>;
  try {
    payload = event.body ? JSON.parse(event.body) : {};
  } catch {
    return { statusCode: 400, headers: CORS, body: JSON.stringify({ error: "Malformed JSON body" }) };
  }

  const opportunityId = payload.opportunityId;
  const versionRaw = payload.versionRaw;
  const attemptId = payload.attemptId;
  const templateId = payload.templateId;
  if (
    typeof opportunityId !== "string" || opportunityId === "" ||
    typeof versionRaw !== "string" || versionRaw === "" ||
    typeof attemptId !== "string" || attemptId === "" ||
    typeof templateId !== "string" || templateId === ""
  ) {
    return { statusCode: 400, headers: CORS, body: JSON.stringify({ error: "Missing or malformed opportunityId/versionRaw/attemptId/templateId" }) };
  }

  // The declared templateId is checked against the CONFIGURED one here
  // too (defense in depth -- the actual outbound body below overrides it
  // regardless) so a caller who declares the wrong template is refused
  // with a clear reason rather than silently having it swapped.
  if (templateId !== DOCUMENTS_CONTRACTS.templateId) {
    return { statusCode: 400, headers: CORS, body: JSON.stringify({ error: "Declared templateId does not match the configured templateId", by: "iaos-contract-send-execute-test-only" }) };
  }

  const token = process.env.GHL_PRIVATE_API_KEY;
  if (!token) {
    return { statusCode: 500, headers: CORS, body: JSON.stringify({ error: "GHL_PRIVATE_API_KEY not configured" }) };
  }
  const headers = { Authorization: `Bearer ${token}`, Version: "2021-07-28", "Content-Type": "application/json" };

  const notesRes = await fetch(`${GHL_BASE}/contacts/${DOCUMENTS_CONTRACTS.approvedTestContactId}/notes`, { headers });
  if (!notesRes.ok) {
    const text = await notesRes.text();
    return { statusCode: 502, headers: CORS, body: JSON.stringify({ error: "Could not read existing notes to verify the reservation ticket", detail: text }) };
  }
  const notesBody = await notesRes.json();
  const notes: { body: string }[] = Array.isArray(notesBody?.notes) ? notesBody.notes : [];

  // TICKET LOOKUP. No note for this exact attemptId at all -- no
  // reservation was ever made; this is exactly the "missing
  // authorization" / "direct call bypassing reservation" case item 4
  // exists to close.
  const attempt = resolveAttemptByExactId(notes, attemptId);
  if (!attempt) {
    return {
      statusCode: 403,
      headers: CORS,
      body: JSON.stringify({ error: "No reservation ticket exists for this attemptId -- a send may only be executed after a successful reservation", by: "iaos-contract-send-execute-test-only" }),
    };
  }
  // TICKET IDENTITY. The resolved ticket must actually be FOR the
  // declared opportunity/version/template -- a caller cannot present a
  // real attemptId that was reserved for a DIFFERENT deal or revision
  // and redeem it against this one ("forged"/"revision mismatch").
  if (attempt.opportunityId !== opportunityId || attempt.versionRaw !== versionRaw || attempt.requestedTemplateId !== templateId) {
    return {
      statusCode: 403,
      headers: CORS,
      body: JSON.stringify({ error: "The reservation ticket does not match the declared opportunityId/versionRaw/templateId", by: "iaos-contract-send-execute-test-only" }),
    };
  }
  // TICKET FRESHNESS -- SINGLE USE. Anything other than the bare
  // "in_progress" state means this ticket has ALREADY been consumed by
  // an earlier execution (a resolution note already exists for this
  // exact attemptId) -- refused, closing replay/double-invocation once
  // the client has written its own resolution note.
  if (attempt.status !== "in_progress") {
    return {
      statusCode: 409,
      headers: CORS,
      body: JSON.stringify({ error: "This reservation ticket has already been consumed", status: attempt.status, by: "iaos-contract-send-execute-test-only" }),
    };
  }

  // INDEPENDENT RE-VERIFICATION. Never trust that reservation's own
  // authorization check still holds by the time execution runs -- redo
  // it here, against the SAME freshly-read notes, narrowing the window
  // between the two calls rather than assuming nothing changed.
  const authCheck = verifyServerSideAuthorization({
    notes,
    opportunityId,
    declaredVersionRaw: versionRaw,
    expectedTemplateName: DOCUMENTS_CONTRACTS.expectedTemplateName,
  });
  if (!authCheck.ok) {
    return {
      statusCode: 403,
      headers: CORS,
      body: JSON.stringify({ error: "Server-side authorization verification failed", reason: authCheck.reason, message: authCheck.message, by: "iaos-contract-send-execute-test-only" }),
    };
  }

  // Every check passed -- forward the real send. contactId/userId/
  // templateId are ALL from config, never from the caller.
  const outboundBody = JSON.stringify({
    templateId: DOCUMENTS_CONTRACTS.templateId,
    locationId: LOCATION_ID,
    sendDocument: true,
    contactId: DOCUMENTS_CONTRACTS.approvedTestContactId,
    userId: DOCUMENTS_CONTRACTS.senderUserId,
    opportunityId,
  });
  const sendRes = await fetch(`${GHL_BASE}/proposals/templates/send`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, Version: "v3", "Content-Type": "application/json" },
    body: outboundBody,
  });
  const sendBody = await sendRes.text();
  return {
    statusCode: sendRes.status,
    headers: { ...CORS, "Content-Type": "application/json" },
    body: sendBody,
  };
};
